#!/usr/bin/env python3.6

import requests
from selenium.webdriver import Chrome
from selenium.webdriver import ChromeOptions
from selenium.webdriver.support.wait import WebDriverWait
from bs4 import BeautifulSoup
from selenium.common.exceptions import NoSuchElementException
from sys import argv
from os import mkdir

url = argv[1]

options = ChromeOptions()
options.headless = True

while True:
	try:
		driver = Chrome(executable_path='/home/aaron/Downloads/chromedriver', options=options)
		driver.get(url)
		wait = WebDriverWait(driver, 20)
		title = driver.find_element_by_class_name("css-v3d350").text
		description = driver.find_element_by_class_name("content__u3I1").get_attribute('innerHTML')
		break
	except NoSuchElementException as e:
		print(e)

title = title.split(".")
title = f"{int(title[0]):04d}.{title[1]}"
full_path = f"/home/aaron/Projects/LeetCode/{title}"
mkdir(full_path)
with open(f"{full_path}/s.py", mode='w') as f:
	print('from typing import List\n\n\n\n# print(Solution())', file=f)
with open(f"{full_path}/README.md", mode='w') as f:
	print(description, file=f)



# from sys import argv
# from os import mkdir, listdir


# argv[1] = f"{int(float(argv[1])):04d}."
# dir_name = ' '.join(argv[1:])
# full_path = f"/home/aaron/Projects/LeetCode/{dir_name}"
# mkdir(full_path)
# with open(f"{full_path}/s.py", mode='w') as f:
	# print('from typing import List\nfrom sys import argv as argv\n\n\n\n# argv[1]\n# print(Solution())', file=f)



# args="$@"
# mkdir ~/Projects/LeetCode/"$args"
# cd ~/Projects/LeetCode/"$args"
# echo -e 'from typing import List\nfrom sys import argv as argv\n\n\n\n# argv[1]\n# print(Solution())' >> s.py
# pwd
