#!/bin/bash

# todo:
# 	save rants into file
#   	Maybe even save each rant into its own file? I think that that seems like
# 			a better optionj
#   rant -l allows to scroll through list of previous rants.

while true; do
	read -e line
	if [ "$line" == "exit" ]; then
		exit 0
	fi
done
